# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev1+gf6032a5.d20220815'
__version_tuple__ = version_tuple = (0, 1, 'dev1', 'gf6032a5.d20220815')
